version: "3.8"
services:
    auth_server:
        image: alan451/flask-api:0.0.1
        command: sh -c "export FLASK_APP=server.py && export FLASK_ENV=development && flask run --host=0.0.0.0"
        ports:
        - "5000:5000"
        container_name: auth_server-old
        env_file: 
            - ./microservices/auth_server/.env
        # volumes:
        # - ./microservices/auth_server/:/code/micro/auth/   
        # depends_on: 
        #     - nextjs-ui      
    nextjs-ui:
        image: alan451/next-app:0.0.1
        command: npm run dev
        ports:
        - "3000:3000"
        container_name: nextjs-ui-old
        # volumes:
        # - ./client:/code/client
        # - /code/client/node_modules
